# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, max_length=12)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('is_company', models.BooleanField()),
                ('is_contact', models.BooleanField()),
                ('added_date', models.DateField(auto_now=True)),
                ('added_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(max_length=12)),
                ('server_os', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('server_name', models.CharField(max_length=255)),
                ('public_ip', models.CharField(max_length=100)),
                ('private_ip', models.CharField(max_length=100)),
                ('alert_sender_email1', models.EmailField(max_length=100)),
                ('alert_sender_email2', models.EmailField(blank=True, max_length=100)),
                ('alert_sender_email3', models.EmailField(blank=True, max_length=100)),
                ('escalate_to_email1', models.EmailField(max_length=100)),
                ('escalate_to_email2', models.EmailField(blank=True, max_length=100)),
                ('added_date', models.DateField(auto_now=True)),
                ('added_by', models.IntegerField(max_length=12)),
                ('deleted', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=255)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
                ('insert_date', models.DateField(auto_now=True)),
                ('inserted_by', models.BigIntegerField()),
            ],
        ),
    ]
