# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='added_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='deleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companyserver',
            name='added_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companyserver',
            name='company_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companyserver',
            name='deleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
