# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0002_auto_20171126_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyserver',
            name='deleted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
