# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0002_auto_20171008_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyMaster',
            new_name='Company',
        ),
    ]
