# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0003_employee_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='insert_date',
        ),
    ]
