# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0003_auto_20171010_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
