# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0004_auto_20171010_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allow_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
