# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0005_branch_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Autotriage.Branch'),
            preserve_default=False,
        ),
    ]
