# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotriage', '0006_contact_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
